# config file for automatic testing at travis-ci.org
language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"
  - "pypy"

install:
  # install dependencies
  - pip install -r requirements/development.txt --use-mirrors
  - pip install coveralls

  # install your own package + executables
  - pip install --editable .

script:
  # command to run tests and collect test coverage
  - coverage run --source chanjo setup.py test

after_success:
  coveralls
