# config file for automatic testing at travis-ci.org
language: python

python:
    - "3.4"
    - "3.3"
    - "2.7"
    - "pypy"

install:
    # install dependencies
    - pip install -r requirements/development.txt

    # install your own package + executables
    - pip install --editable .

script:
    # command to run tests and collect test coverage
    - py.test --flakes --cov-report html --cov {{ cookiecutter.repo_name|replace('-', '_') }} tests/

notifications:
    email: false

after_success:
    coveralls
